config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get '/search', to: 'search#search'
  get 'answers/edit'
  get 'comments/edit'

  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'

  get 'home/about'

  resources :posts do
    resource :post_likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  get 'posts/:id/comments/:comment_id' => 'posts#show'
  get 'posts/:id/comments' => 'posts#show'
  post 'comments/:id/comment_likes' => 'comment_likes#create',as: 'post_comments_comment_likes'
  delete 'comments/:id/comment_likes' => 'comment_likes#destroy',as: 'destroy_comment_likes'

  resources :questions do
    resource :empathies, only: [:create, :destroy]
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  get 'questions/:id/answers/:answer_id' => 'questions#show'
  get 'questions/:id/answers' => 'questions#show'
  post 'answers/:id/answer_likes' => 'answer_likes#create',as: 'question_answers_answer_likes'
  delete 'answers/:id/answer_likes' => 'answer_likes#destroy', as: 'destroy_answer_likes'

  resources :users,only: [:show,:edit,:update,:index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :notifications, only: :index do
    collection do
      delete '/', to: 'notifications#destroy_all'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # 投稿,質問ランキング(3位まで),モデルに定義
  def top
    @post_like_ranks = Post.create_post_like_ranks
    @question_empathies_ranks = Question.create_question_empathy_ranks
  end

  def about
  end

  def new_guest
    user = User.find_or_create_by!(name: 'guest', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました！'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <div class="rogo"><strong>子育てネット</strong>とは</div>
      <div class="about_title">子育てをもっと楽しく</div>
      <div class="indent">
        このサイトは、子育てや保育経験者の方、現在子育てをしている人をはじめ様々な人がつながって網のようになり、子育てをしている一人ひとりの不安や孤独感を解消したいという思いから<strong>「子育てネット」</strong>と名付けました。
      </div>
      <div class="about_heading">子育てネットの2つの特徴</div>
      <div class="about_list">01. 投稿やコメントで子育ての体験を共有できる</div>
      <div class="indent"><%= link_to "投稿の一覧画面を見る", posts_path %></div>
      <div class="about_list">02. 質問や回答で子育ての悩みを相談し、アドバイスをもらうことができる</div>
      <div class="indent"><%= link_to "質問一覧を見る", questions_path %></div>
      <div class="about_heading">子育てネットの便利＆楽しみ方</div>
      <div class="about_list">01. 質問者に対して、一人じゃないよと伝えられる</div>
      <div class="indent">
        質問には、<i class="fas fa-smile" aria-hidden="true"></i>「共感した」ボタンがついていて、そのボタンを押すことで質問者に同じようなことで悩んでいる人がいること、共感してくれる人がいることを伝えることができます。
      </div>
      <div class="about_list">02. 気になるタグで検索できる</div>
      <div class="indent">
        投稿や質問にはいろいろなタグが付いています。<br>
        自分の探しているもの、気になったものをぜひ検索してみてください！</div>
        <div class="about_list">03. チャットができる</div>
      <div class="indent">
        チャットで気になる会員とメッセージを送り合うことができます。</div>
    </div>
    <div class="col-md-3 col-sm-12 search">
      <%= render 'posts/search' %>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <div class="col-md-9 col-sm-12">
    <% else %>
      <div class="col-md-12 col-sm-12">
    <% end %>
      <div class="flash_message h5"><%= flash[:notice] %></div>
      <div class="top-heading h3">投稿ランキング</div>
      <div class="top-heading h3">
        （ <i class="fas fa-thumbs-up" aria-hidden="true"></i> いいね順）トップ３
      </div>
      <table class="top-table table table-hover table-inverse">
        <thead>
          <tr>
            <th class="th-01"><i class="fas fa-thumbs-up" aria-hidden="true"></i> </th>
            <th class="th-02">名前</th>
            <th class="th-03">タイトル</th>
            <th class="th-04">タグ</th>
          </tr>
        </thead>
        <tbody>
          <% @post_like_ranks.each do |post| %>
            <tr>
              <td>
                <i class="fas fa-thumbs-up" aria-hidden="true"></i><%= post.post_likes.count %>
              </td>
              <td>
                <%= link_to user_path(post.user_id) do %>
                   <%= attachment_image_tag(post.user, :profile_image, :fill, 40, 40, fallback: "no-image1.jpg") %><br>
                <% end %>
                <%= link_to post.user.name, user_path(post.user_id) %>
              </td>
              <td>
                <%= link_to post.title, post_path(post) %><br>
                <%= post.created_at.strftime("%Y/%m/%d") %>
              </td>
              <td>
                <% post.tag_list.each do |tag| %>
                  <%= link_to tag, posts_path(tag_name: tag), class: 'button btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="top-heading h3">質問ランキング</div>
      <div class="top-heading h3">
        （ <i class="fas fa-smile" aria-hidden="true"></i> 共感した順）トップ３
      </div>
      <table class="top-table table table-hover table-inverse">
        <thead>
          <tr>
            <th class="th-01"><i class="fas fa-smile" aria-hidden="true"></i> </th>
            <th class="th-02">名前</th>
            <th class="th-03">タイトル</th>
            <th class="th-04">タグ</th>
          </tr>
        </thead>
        <tbody>
          <% @question_empathies_ranks.each do |question| %>
            <tr>
              <td>
                <i class="fas fa-smile" aria-hidden="true"></i>
                <%= question.empathies.count %>
              </td>
              <td>
                <%= link_to user_path(question.user_id) do %>
                  <%= attachment_image_tag(question.user, :profile_image, :fill, 40, 40, fallback: "no-image1.jpg") %><br>
                <% end %>
                <%= link_to question.user.name, user_path(question.user_id) %>
              </td>
              <td>
                <%= link_to question.title, question_path(question) %><br>
                <%= question.created_at.strftime("%Y/%m/%d") %>
              </td>
              <td>
                <% question.tag_list.each do |tag| %>
                  <%= link_to tag, questions_path(tag_name: tag), class: 'button btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3 col-sm-12 search">
      <%= render 'posts/search' %>
    </div>
  </div>
</div>