config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get '/search', to: 'search#search'
  get 'answers/edit'
  get 'comments/edit'

  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'

  get 'home/about'

  resources :posts do
    resource :post_likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  get 'posts/:id/comments/:comment_id' => 'posts#show'
  get 'posts/:id/comments' => 'posts#show'
  post 'comments/:id/comment_likes' => 'comment_likes#create',as: 'post_comments_comment_likes'
  delete 'comments/:id/comment_likes' => 'comment_likes#destroy',as: 'destroy_comment_likes'

  resources :questions do
    resource :empathies, only: [:create, :destroy]
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  get 'questions/:id/answers/:answer_id' => 'questions#show'
  get 'questions/:id/answers' => 'questions#show'
  post 'answers/:id/answer_likes' => 'answer_likes#create',as: 'question_answers_answer_likes'
  delete 'answers/:id/answer_likes' => 'answer_likes#destroy', as: 'destroy_answer_likes'

  resources :users,only: [:show,:edit,:update,:index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :notifications, only: :index do
    collection do
      delete '/', to: 'notifications#destroy_all'
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :answer, presence: true, length: {maximum: 200}
  has_many :answer_likes, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def answer_liked_by?(user)
    answer_likes.where(user_id: user.id).exists?
  end

  # コメントをいいね順に並べるメソッド
  def self.answer_like_ranks(question_id)
    question = Question.find(question_id)
    question.answers.joins(:answer_likes).group(:answer_id).order('count(answer_likes.answer_id) desc')
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @question_new = Question.new
    @answer = Answer.new(answer_params)
    @answer.question_id = @question.id
    @answer.user_id = current_user.id
    @answer_question = @answer.question
    if @answer.save
      flash[:answer] = "回答しました！"
      #通知の作成
      @answer_question.create_notification_answer!(current_user, @answer.id)
    end
    @answers = @question.answers
    render 'create.js.erb' #テストに必要
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:answer] = "回答を編集しました！"
      redirect_to question_path(@answer.question)
    else
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @question = @answer.question
    if @answer.user != current_user
      redirect_to request.referer
    end
    @answer.destroy
    flash[:answer] = "回答を削除しました！"
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/create.js.erb
$("textarea").val("");
$(".question_<%= @question.id %>").html("<%= j( render 'questions/show', question: @question ) %>");
$(".answer_errors").html("<%= j( render 'layouts/errors', obj: @answer ) %>");
$(".answer_<%= @question.id %>").html("<%= j( render 'questions/answers', answers: @answers.order(created_at: :desc).page(params[:page]) ) %>");

app/views/answers/destroy.js.erb
$(".question_<%= @question.id %>").html("<%= j( render 'questions/show', question: @question ) %>");
$(".answer_<%= @question.id %>").html("<%= j( render 'questions/answers', answers: @question.answers.order(created_at: :desc).page(params[:page]) ) %>");

app/views/answers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <h3>回答編集</h3>
      <%= render 'layouts/errors', obj: @answer %>
      <%= form_with(model: @answer, url: question_answer_path(@answer.question,@answer), method: :patch, local: true) do |f| %>
        <%= f.text_area :answer, class: "form-control" %>
        <div class="actions">
          <%= f.submit '変更する', class: 'btn btn-primary col-xs-12' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-3 col-sm-12 search">
      <%= render 'posts/search' %>
    </div>

  </div>
</div>