config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get '/search', to: 'search#search'
  get 'answers/edit'
  get 'comments/edit'

  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'

  get 'home/about'

  resources :posts do
    resource :post_likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  get 'posts/:id/comments/:comment_id' => 'posts#show'
  get 'posts/:id/comments' => 'posts#show'
  post 'comments/:id/comment_likes' => 'comment_likes#create',as: 'post_comments_comment_likes'
  delete 'comments/:id/comment_likes' => 'comment_likes#destroy',as: 'destroy_comment_likes'

  resources :questions do
    resource :empathies, only: [:create, :destroy]
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  get 'questions/:id/answers/:answer_id' => 'questions#show'
  get 'questions/:id/answers' => 'questions#show'
  post 'answers/:id/answer_likes' => 'answer_likes#create',as: 'question_answers_answer_likes'
  delete 'answers/:id/answer_likes' => 'answer_likes#destroy', as: 'destroy_answer_likes'

  resources :users,only: [:show,:edit,:update,:index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :notifications, only: :index do
    collection do
      delete '/', to: 'notifications#destroy_all'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.order(created_at: :desc).page(params[:page])
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(:user_id => current_user.id).page(params[:page]).reverse_order
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <h3>チャット相手の一覧</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th class="th-02">名前</th>
            <th class="th-04"></th>
            <th class="th-04"></th>
          </tr>
        </thead>
        <tbody>
          <% @anotherEntries.each do |e| %>
            <tr>
              <td>
                <%= link_to user_path(e.user) do %>
                  <%= attachment_image_tag(e.user, :profile_image, :fill, 40, 40, fallback: "no-image1.jpg") %><br>
                <% end %>
                <%= link_to e.user.name, user_path(e.user) %>
              </td>
              <td>
                <%= link_to room_path(e.room.id) do %>
                  <i class="fas fa-paper-plane"> チャットへ</i>
                <% end %>
              </td>
              <td>
                <!-- フォローボタン -->
                <% if current_user.id != e.user.id %>
                  <% if current_user.following?(e.user) %>
                    <%= link_to 'フォロー外す', user_relationships_path(e.user.id), method: :delete, class: "btn btn-primary" %>
                  <% else %>
                    <%= link_to 'フォローする', user_relationships_path(e.user.id), method: :POST, class: "btn btn-success" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @anotherEntries %>
    </div>

    <div class="col-md-3 col-sm-12 search">
      <%= render 'posts/search' %>
    </div>

  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <div class="chats_area">
        <% @entries.each do |entry| %>
          <% if current_user != entry.user %>
            <h4><strong><%= link_to entry.user.name, user_path(entry.user) %>さんとのチャットルームです</strong></h4>
          <% end %>
        <% end %>
        <br>

        <%= form_for @message do |f| %>
          <%= f.text_field :content, :placeholder => "メッセージを入力して下さい", class: "form-control" %>
          <%= f.hidden_field :room_id, :value => @room.id %>
          <div class="actions">
            <%= f.submit "送信", class: 'btn btn-primary col-xs-12'%>
          </div>
        <% end %>

        <hr>
        <% if @messages.present? %>
          <% @messages.each do |message| %>
            <% if current_user == message.user %>
              <div class="my_message_area">
                <div class="message my_message">
                  <%= safe_join(message.content.split("\n"), tag(:br)) %>
                  <!-- safe_joinによって改行が反映される -->
                </div><br>
                <div class="message_time">
                  <%= message.created_at.strftime("%m/%d %H:%M") %><br>
                </div>
              </div>
            <% else %>
              <div class="message other_message">
                <%= safe_join(message.content.split("\n"), tag(:br)) %>
              </div><br>
              <div class="message_time">
                <%= message.created_at.strftime("%m/%d %H:%M") %><br>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <h4 class="text_center">メッセージはありません</h4>
        <% end %>
        <%= paginate @messages %>
      </div>
    </div>

    <div class="col-md-3 col-sm-12 search">
      <%= render 'posts/search' %>
    </div>

  </div>
</div>